theme: jekyll-theme-minimal
title: Fantasy Football Prediction Collection
description: agkna,sdnfa,ksdnfja
show_downloads: False
navigation:
  - title: Grundle Me This
    url: league_GrundleMeThis
  - title: Auction League
    url: league_AuctionLeague
  - title: Lynn Family League
    url: league_LynnFamilyLeague
  - title: PB League
    url: league_PBLeague
